Repository TheLaendOfAdventure/The-Laend-of-Adventure, pull requests merged in 2023-06, with the labels that each got.

#81 Loa 204 quest dialogs content
  app/src/main/assets/conversations/BrückenTrollRiddle.json
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/data/dao/QuestDao.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/data/offlinerepository/OfflineQuestRepository.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/data/repository/QuestRepository.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/logic/QuestLogic.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/dialogpopup/ConversationPopupDialog.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/helper/MapHelper.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/popupwindow/ConversationPopupDialog.kt
  app/src/main/res/layout/conversation_popup.xml
Labels: enhancement

#82 Loa 304 display all badges greyed out
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/adapters/BadgesAdapter.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/fragments/BadgesPageFragment.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/viewmodels/BadgesPageViewModel.kt
  app/src/main/res/layout/fragment_badges_page.xml
Labels: enhancement

#83 LOA-323 Dialog paths now only need to be the file without the package they are in
  app/src/main/assets/database/Laend_of_Adventure.db
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/helper/MapHelper.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/popupwindow/ConversationPopupDialog.kt
Labels: enhancement

#84 LOA-314 Change the user image implementation to Glide
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/fragments/MainPageFragment.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/fragments/UserPageFragment.kt
Labels: enhancement

#86 Loa 280 dynamic riddle answer options
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/data/dao/QuestDao.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/data/dao/datahelper/RiddleDetails.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/adapters/RiddleAnswerAdapter.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/dialogpopup/RiddlePopupDialog.kt
  app/src/main/res/layout/dialog_riddle_popup.xml
  app/src/main/res/layout/riddle_popup_listitem.xml
Labels: enhancement

#87 Loa 333 notification upon quest completion
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/data/dao/QuestDao.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/data/offlinerepository/OfflineQuestRepository.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/data/repository/QuestRepository.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/logic/QuestLogic.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/helper/SnackbarHelper.kt
  app/src/main/res/layout/snackbar_default.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#88 LOA-274 converted hint to text
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/fragments/UserPageFragment.kt
Labels: bug

#89 Loa 189 implement font
  app/src/main/res/font/bold.otf
  app/src/main/res/font/bold_italic.otf
  app/src/main/res/font/italic.otf
  app/src/main/res/font/minecraft_regular.xml
  app/src/main/res/font/regular.otf
  app/src/main/res/values/themes.xml
Labels: enhancement

#91 Loa 329 notification upon goal completion
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/data/dao/QuestDao.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/data/offlinerepository/OfflineQuestRepository.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/data/repository/QuestRepository.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/logic/QuestLogic.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#90 Loa 335 main page styling
  app/src/main/res/drawable/frame.webp
  app/src/main/res/drawable/level_frame.webp
  app/src/main/res/layout/fragment_main_page.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#92 Loa 327 notification upon badge receipt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/data/dao/BadgeDao.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/data/offlinerepository/OfflineBadgeRepository.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/data/repository/BadgeRepository.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/logic/QuestLogic.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#94 Loa 275 badge progress
  app/src/main/assets/database/Laend_of_Adventure.db
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/data/AppDatabase.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/data/dao/BadgeDao.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/data/entity/UserBadgeEntity.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/data/offlinerepository/OfflineBadgeRepository.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/data/repository/BadgeRepository.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/logic/QuestLogic.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/adapters/BadgesAdapter.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/fragments/BadgesPageFragment.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/viewmodels/BadgesPageViewModel.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/viewmodels/UserCreationViewModel.kt
  app/src/main/res/layout/badgespage_listitem.xml
Labels: bug, enhancement

#95 Loa 338 implement quest page styling
  app/src/main/res/drawable/background_book.webp
  app/src/main/res/drawable/tab_bookmark.webp
  app/src/main/res/drawable/text_background.webp
  app/src/main/res/layout/fragment_quest_page.xml
  app/src/main/res/layout/questpage_listitem.xml
Labels: enhancement

#96 Loa 353 snackbars should not overlap each other
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/data/dao/BadgeDao.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/data/offlinerepository/OfflineBadgeRepository.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/data/repository/BadgeRepository.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/data/repository/QuestRepository.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/logic/QuestLogic.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/logic/UserLogic.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/helper/SnackbarHelper.kt
Labels: enhancement

#98 Loa 330 fix elivs operator
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/data/repository/QuestRepository.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/logic/QuestLogic.kt
Labels: bug

#97 Loa 320 add flaming logic
  app/src/main/assets/database/Laend_of_Adventure.db
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/data/AppDatabase.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/data/dao/BadgeDao.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/data/dao/UserDao.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/data/entity/StatTrackingEntity.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/data/entity/UserEntity.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/data/offlinerepository/OfflineBadgeRepository.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/data/offlinerepository/OfflineUserRepository.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/data/repository/BadgeRepository.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/data/repository/UserRepository.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/logic/BadgeLogic.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/logic/QuestLogic.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/logic/UserLogic.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/dialogpopup/RiddlePopupDialog.kt
Labels: enhancement

#101 Loa 365 blaesshuhn quest
  app/src/main/assets/conversations/blaesshuhn_accept_quest_dialogue.json
  app/src/main/assets/conversations/blaesshuhn_complete_quest_dialogue.json
  app/src/main/assets/conversations/hinweise_der_weisen_Kräuterfrau.json
  app/src/main/assets/conversations/koeniglicher_Jaeger.json
  app/src/main/assets/conversations/rätsel_der_weisen_Kräuterfrau.json
  app/src/main/assets/database/Laend_of_Adventure.db
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/data/dao/QuestDao.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/data/dao/datahelper/RiddleDetails.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/logic/QuestLogic.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/logic/TrackingLogic.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/adapters/QuestAdapter.kt
Labels: enhancement

#99 LOA-352 Fix Glide
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/fragments/BadgesPageFragment.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/fragments/MainPageFragment.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/fragments/QuestPageFragment.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/fragments/UserCreationFragment.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/fragments/UserPageFragment.kt
Labels: bug

#103 Loa 332 put icons into drawable
  app/src/main/assets/database/Laend_of_Adventure.db
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/adapters/BadgesAdapter.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/helper/MapHelper.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/popupwindow/ConversationPopupDialog.kt
  app/src/main/res/drawable/badge1img.webp
Labels: enhancement

#107 LOA-370 added Brotgelehrter Badge
  app/src/main/assets/database/Laend_of_Adventure.db
Labels: enhancement

#102 Loa 326 fix camera position reset
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/fragments/MainPageFragment.kt
  app/src/main/res/layout/fragment_main_page.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#113 Loa 341 implement badge page styling
  app/src/main/res/drawable/badge_page_background.webp
  app/src/main/res/layout/badgespage_listitem.xml
  app/src/main/res/layout/fragment_badges_page.xml
Labels: enhancement

#115 Loa 394 implement user page styling
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/fragments/UserPageFragment.kt
  app/src/main/res/drawable/down_arrow.webp
  app/src/main/res/drawable/feather.webp
  app/src/main/res/drawable/lvl_bar_empty.webp
  app/src/main/res/drawable/lvl_bar_half_full.webp
  app/src/main/res/drawable/text_field_nine.9.png
  app/src/main/res/drawable/user_page_background.webp
  app/src/main/res/layout/fragment_user_page.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#100 LOA-334 Outsource Json reader into JsonHelper.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/helper/JsonHelper.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/helper/MapHelper.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/popupwindow/ConversationPopupDialog.kt
Labels: enhancement

#117 LOA-383-Read-NPC-img-from-json
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/logic/QuestLogic.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/helper/JsonHelper.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/popupwindow/ConversationPopupDialog.kt
Labels: enhancement

#114 Loa 296 add user id singleton
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/data/dao/UserDao.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/data/offlinerepository/OfflineUserRepository.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/data/repository/UserRepository.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/logic/BadgeLogic.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/logic/QuestLogic.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/logic/TrackingLogic.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/logic/UserLogic.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/adapters/BadgesAdapter.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/dialogpopup/RiddlePopupDialog.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/fragments/MainPageFragment.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/helper/MapHelper.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/helper/SharedPreferencesHelper.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/popupwindow/ConversationPopupDialog.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/viewmodels/BadgesPageViewModel.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/viewmodels/MainPageViewModel.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/viewmodels/QuestPageViewModel.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/viewmodels/UserCreationViewModel.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/viewmodels/UserPageViewModel.kt
Labels: enhancement

#110 Loa 324 check player location for accepting quest
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/data/dao/QuestDao.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/logic/TrackingLogic.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/helper/MapHelper.kt
Labels: enhancement

#118 LOA-387 Change to binding
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/helper/JsonHelper.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/popupwindow/ConversationPopupDialog.kt
Labels: enhancement

#119 Loa 398 json reader testing
  app/src/androidTest/java/de/hdmstuttgart/thelaendofadventure/ui/helper/JsonHelperTest.kt
  app/src/main/assets/conversations/negativeTest.json
  app/src/main/assets/conversations/test.json
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/helper/JsonHelper.kt
Labels: test

#116 Loa 335 main page styling
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/fragments/MainPageFragment.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/helper/MapHelper.kt
  app/src/main/res/drawable/compass.webp
  app/src/main/res/drawable/location_puck.webp
  app/src/main/res/drawable/main_page_background.webp
  app/src/main/res/drawable/reset_button.webp
  app/src/main/res/drawable/reset_button_empty.webp
  app/src/main/res/layout/fragment_main_page.xml
Labels: enhancement

#120 LOA-390 changes statTracking table
  app/src/main/assets/database/Laend_of_Adventure.db
Labels: bug

#124 LOA-407 Show shuffled riddleList
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/logic/QuestLogic.kt
Labels: enhancement

#126 Loa 394 implement user page styling
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/fragments/UserPageFragment.kt
  app/src/main/res/drawable/frame.webp
  app/src/main/res/drawable/level_brooch.webp
  app/src/main/res/drawable/map.webp
  app/src/main/res/drawable/profile_top_buttons.webp
  app/src/main/res/drawable/progressbar.xml
  app/src/main/res/drawable/xp_bar.webp
  app/src/main/res/layout/fragment_user_page.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#121 LOA 324 add toast message for if player is too far away
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/logic/TrackingLogic.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/helper/MapHelper.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#130 LOA-410 Add more conversation partners
  app/src/androidTest/java/de/hdmstuttgart/thelaendofadventure/ui/helper/JsonHelperTest.kt
  app/src/main/assets/conversations/test.json
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/helper/JsonHelper.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/popupwindow/ConversationPopupDialog.kt
Labels: enhancement

#122 LOA 344 add conversation popup styling
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/logic/UserLogic.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/helper/MapHelper.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/popupwindow/ConversationPopupDialog.kt
  app/src/main/res/drawable/conversation_field.webp
  app/src/main/res/drawable/scroll.webp
  app/src/main/res/layout/conversation_popup.xml
  app/src/main/res/layout/dialog_conversation_popup.xml
Labels: enhancement

#132 LOA-408 add Icons for Wackelbrücke Quest
  app/src/main/assets/conversations/BrückenTrollRiddle.json
  app/src/main/assets/conversations/RitterBrückenQuest.json
  app/src/main/res/drawable/knight.webp
  app/src/main/res/drawable/troll.webp
Labels: enhancement

#133 Loa 373 add location marker
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/data/dao/QuestDao.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/data/dao/datahelper/Location.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/data/offlinerepository/OfflineQuestRepository.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/data/repository/QuestRepository.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/logic/QuestLogic.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/logic/TrackingLogic.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/dialogpopup/RiddlePopupDialog.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/fragments/MainPageFragment.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/fragments/UserCreationFragment.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/helper/MapHelper.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/popupwindow/ConversationPopupDialog.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/viewmodels/MainPageViewModel.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/viewmodels/UserCreationViewModel.kt
  app/src/main/res/drawable/banner.webp
  app/src/main/res/drawable/img_blank.png
  app/src/main/res/layout/dialog_accept_quest_popup.xml
Labels: enhancement

#136 Icons for blässhuhn quest
  app/src/main/assets/conversations/blaesshuhn_accept_quest_dialogue.json
  app/src/main/assets/conversations/blaesshuhn_complete_quest_dialogue.json
  app/src/main/assets/conversations/hinweise_der_weisen_Kräuterfrau.json
  app/src/main/assets/conversations/koeniglicher_Jaeger.json
  app/src/main/assets/conversations/rätsel_der_weisen_Kräuterfrau.json
  app/src/main/res/drawable/blashuhn_badge.webp
  app/src/main/res/drawable/blashuhn_quest.webp
  app/src/main/res/drawable/herbalist.webp
  app/src/main/res/drawable/hunter.webp
  app/src/main/res/drawable/naturalist.webp
Labels: enhancement

#135 Loa 347 implement chracter creation page styling
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/fragments/UserCreationFragment.kt
  app/src/main/res/drawable/creation_page_background.webp
  app/src/main/res/drawable/empty_avatar.webp
  app/src/main/res/drawable/logo.webp
  app/src/main/res/layout/fragment_user_creation.xml
  app/src/main/res/values/strings.xml
Labels: enhancement
