Repository TheLaendOfAdventure/The-Laend-of-Adventure, pull requests merged in 2023-07, with the labels that each got.

#142 LOA-416 fix badge assignment
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/logic/BadgeLogic.kt
Labels: bug

#140 loa-413 Added KDoc
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/logic/TrackingLogic.kt
Labels: enhancement

#141 LOA-380 Change Image
  app/src/main/res/drawable/badgeedelman.webp
Labels: enhancement

#138 LOA-411 create onClickDismissSnackbar
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/helper/SnackbarHelper.kt
Labels: enhancement

#129 Loa 350 implement riddle popup styling
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/adapters/RiddleAnswerAdapter.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/dialogpopup/RiddlePopupDialog.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/fragments/MainPageFragment.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/helper/MapHelper.kt
  app/src/main/res/anim/shake_animation.xml
  app/src/main/res/anim/zoom_animation.xml
  app/src/main/res/drawable/button.9.png
  app/src/main/res/drawable/conversation_field_nine.9.png
  app/src/main/res/layout/dialog_accept_quest_popup.xml
  app/src/main/res/layout/dialog_riddle_popup.xml
  app/src/main/res/layout/fragment_main_page.xml
  app/src/main/res/layout/riddle_popup_listitem.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#146 Loa 417 change gaumenfreude to level 2
  app/src/main/assets/database/Laend_of_Adventure.db
Labels: enhancement

#137 Loa 364 snackbar styling
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/helper/SnackbarHelper.kt
  app/src/main/res/drawable/snackbar_progressbar.webp
  app/src/main/res/layout/snackbar_default.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#144 Loa 344 fix conversation popup styling
  app/src/main/res/layout/conversation_popup.xml
Labels: enhancement

#134 Loa 341 implement badge page styling
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/fragments/BadgesPageFragment.kt
  app/src/main/res/drawable/badges_top_buttons.webp
  app/src/main/res/layout/badgespage_listitem.xml
  app/src/main/res/layout/fragment_badges_page.xml
  app/src/main/res/layout/questpage_listitem.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#145 Loa 347 adjust character creation styling
  app/src/main/res/layout/fragment_user_creation.xml
Labels: enhancement

#148 Loa 357 progress circle around profile picture
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/fragments/MainPageFragment.kt
  app/src/main/res/drawable/barframe.webp
  app/src/main/res/layout/fragment_main_page.xml
Labels: enhancement

#147 LOA-414 Add UI Tests
  app/build.gradle
  app/src/androidTest/java/de/hdmstuttgart/thelaendofadventure/ui/RenameUserTest.kt
  app/src/androidTest/java/de/hdmstuttgart/thelaendofadventure/ui/UserNameTest.kt
Labels: enhancement

#149 Add license
  LICENSE
Labels: enhancement

#151 Update README.md
  README.md
Labels: enhancement

#153 Loa 360 quest completion icon
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/logic/BadgeLogic.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/logic/QuestLogic.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/logic/TrackingLogic.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/logic/UserLogic.kt
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/ui/helper/SnackbarHelper.kt
  app/src/main/res/drawable/goal_completed_scroll.webp
  app/src/main/res/drawable/quest_accept_scroll.webp
  app/src/main/res/drawable/quest_scroll.webp
  app/src/main/res/layout/snackbar_default.xml
Labels: enhancement

#155 LOA-421-Fix-Ui-Tests
  app/src/androidTest/java/de/hdmstuttgart/thelaendofadventure/ExampleInstrumentedTest.kt
  app/src/androidTest/java/de/hdmstuttgart/thelaendofadventure/ui/RenameUserTest.kt
  app/src/androidTest/java/de/hdmstuttgart/thelaendofadventure/ui/UserNameTest.kt
Labels: bug

#156 Loa 420 update database
  app/src/main/assets/database/Laend_of_Adventure.db
  app/src/main/java/de/hdmstuttgart/thelaendofadventure/logic/BadgeLogic.kt
Labels: enhancement

#157 Fix button bug
  app/src/main/res/layout/dialog_accept_quest_popup.xml
  app/src/main/res/layout/fragment_user_creation.xml
  app/src/main/res/layout/fragment_user_page.xml
Labels: enhancement

#158 Fix scaling issues - popup
  app/src/main/res/layout/dialog_accept_quest_popup.xml
  app/src/main/res/layout/fragment_user_creation.xml
  app/src/main/res/layout/fragment_user_page.xml
Labels: bug, enhancement

#161 Remove unnecessary plugin
  app/build.gradle
Labels: bug

#160 Development
  app/build.gradle
Labels: enhancement
